name: take-home-project

on:
  push:
    branches:
    - master 
  pull_request:
    branches:
      -master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        
        name: download backup
        run: |
        
          Git config --global user.email "thabanglwazi@gmail.com"
          Git config --global user.name "thabanglwazi"
          git clone https://github.com/thabanglwazi/app1.git 
          echo "Hello World - Dockerfile" > c:\inetpub\wwwroot\index.html
        
        
    
