name: take-home-project

on:
  push:
    branches:
    - master 
  pull_request:
    branches:
      -master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
        -name: download backup
        run: |
        
          Git config --global user.email "thabanglwazi@gmail.com"
          PS C:\> Git config --global user.name "thabanglwazi"
          PS C:\> git clone https://github.com/thabanglwazi/app1.git 
        
        shell: pwsh
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
